### ISSUE TITLE
TermsOrPrivacyTemplate を src/templates/index.ts に含めるとBuildエラーが発生する

### ISSUE THREAD

**Issue by keitakn** [nekochans/lgtm-cat-ui#105]
# 概要

表題の通りでStorybook上で正常動作している `TermsOrPrivacyTemplate` を `src/templates/index.ts` に追加してexportするとBuildエラーが発生する。

```
[!] (plugin commonjs--resolver) TypeError: Cannot read properties of undefined (reading 'file')
TypeError: Cannot read properties of undefined (reading 'file')
    at Object.onwarn (/home/runner/work/lgtm-cat-ui/lgtm-cat-ui/rollup.config.js:50:23)
    at /home/runner/work/lgtm-cat-ui/lgtm-cat-ui/node_modules/rollup/dist/shared/mergeOptions.js:100:25
    at Object.onwarn (/home/runner/work/lgtm-cat-ui/lgtm-cat-ui/node_modules/rollup/dist/shared/rollup.js:23216:13)
    at Object.warn (/home/runner/work/lgtm-cat-ui/lgtm-cat-ui/node_modules/rollup/dist/shared/rollup.js:22660:21)
    at doResolveId (/home/runner/work/lgtm-cat-ui/lgtm-cat-ui/node_modules/@rollup/plugin-node-resolve/dist/cjs/index.js:1122:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.resolveId (/home/runner/work/lgtm-cat-ui/lgtm-cat-ui/node_modules/@rollup/plugin-node-resolve/dist/cjs/index.js:1180:24)
    at resolveId (/home/runner/work/lgtm-cat-ui/lgtm-cat-ui/node_modules/rollup/dist/shared/rollup.js:218[44](https://github.com/nekochans/lgtm-cat-ui/runs/7612131871?check_suite_focus=true#step:4:45):26)
    at ModuleLoader.resolveId (/home/runner/work/lgtm-cat-ui/lgtm-cat-ui/node_modules/rollup/dist/shared/rollup.js:22144:19)
```

# 再現手順

1. `TermsOrPrivacyTemplate` を `src/templates/index.ts` に追加する
2. `npm run build` を実行する

# 再現環境

最新バージョンで発生。

# このバグによって引き起こされる問題

このままだと `TermsOrPrivacyTemplate` をexport出来ないので、Packageの利用者側が `TermsOrPrivacyTemplate` 相当のTemplateを作成する必要が出てくる。

他のComponentと設計の差異が出るので出来れば本件を解決したい。

# スクリーンショット、エラーメッセージ

なし

# 補足情報

なし

**Comment by keitakn** [comment]
どうも `ReactMarkdown` をimportしている事が原因のようだ。

`ReactMarkdown` をコメントアウトしたらBuildエラーが消えた。

```
> @nekochans/lgtm-cat-ui@0.8.0 build
> rm -rf dist && rollup -c


src/index.ts → dist/cjs/index.js, dist/esm/index.js...
created dist/cjs/index.js, dist/esm/index.js in 8.8s

dist/esm/types/index.d.ts → dist/index.d.ts...
created dist/index.d.ts in 139ms
```

**Comment by keitakn** [comment]
>This package is [ESM only](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). In Node.js (version 12.20+, 14.14+, or 16.0+), install with [npm](https://docs.npmjs.com/cli/install):

https://github.com/remarkjs/react-markdown

このあたりが関係ありそうだ。

だからCommonJS形式でのBuildが出来ないのか・・・

**Comment by keitakn** [comment]
色々考えたが `TermsOrPrivacyTemplate` をexportする方向でChildrenを受け取る形で落ち着いた。

これであれば `react-markdown` が含まれないので、Buildも正常に行う事が出来る。
